Products:
  ipd:
    name: "Super iPad"
    price: 549.99
  mbp:
    name: "MacBook Pro"
    price: 1399.99
  atv:
    name: "Apple TV"
    price: 109.50
  vga:
    name: "VGA adapter"
    price: 30.00

Specials:
  - "3 atv = 2 atv"
  - "4 ipd = $499.99"
  - "1 mbp > 1 vga"
  - "5 vga = 4 vga"
